services:
  app:
    tty: true
    networks:
      - app_network
    build:
      context: .
    ports:
      - '3000:3000'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    depends_on:
      - db

  db:
    image: postgres:15
    hostname: db
    env_file:
      - ./.env
    networks:
      - app_network
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql
      - ./sql:/docker-entrypoint-initdb.d

networks:
  app_network:
    driver: bridge
volumes:
  node_modules:
