export type EmployeeType = {
  id: number;
  sei: string;
  sei_k: string;
  mei: string;
  mei_k: string;
  gender: string;
  phone_number: string;
  email: string;
  address: string;
  birthday: string;
  joining_date: string;
  retirement_date: string;
  client_id: number;
  employee_skills_id: number;
  employment_id: number;
  job_category_id: number;
  position_id: number;
  postal_code: string;
  project_id: number;
  remarks: string;
};
